# sudoku solver

In [5]:
from collections import defaultdict
import numpy as np

In [22]:
Grid = [[2,0,3,0,9,4,0,6,0],
       [0,0,0,0,1,0,0,9,2],
       [0,6,0,8,3,0,4,0,0],
       [9,8,0,0,0,0,7,0,3],
       [3,0,5,0,0,8,0,0,6],
       [7,0,0,3,0,6,2,8,9],
       [0,1,2,7,0,0,9,0,0],
       [0,0,0,0,4,0,5,1,8],
       [0,0,0,0,0,0,0,0,0],
       ]
rows=defaultdict(set)
cols=defaultdict(set)
squares=defaultdict(set)
for i in range(0,9):
    for j in range(0,9):
        if Grid[i][j]==0:
            continue
        if Grid[i][j] not in rows[i]:
            rows[i].add(Grid[i][j])
        if Grid[i][j] not in cols[j]:
            cols[j].add(Grid[i][j])
        x=i//3
        y=j//3
        if Grid[i][j] not in squares[(x,y)]:
            squares[(x,y)].add(Grid[i][j])

In [23]:
def ifpossible(x,y,n):
    global Grid    
    global rows
    global cols
    global squares
    if (n in rows[x]) or (n in cols[y]) or (n in squares[(x//3,y//3)]):
        return False
    return True

In [24]:
def solve():
    global Grid
    global rows
    global cols
    global squares
    for i in range(0,9):
        for j in range(0,9):
            if Grid[i][j]==0:
                for n in range(1,10):
                    if ifpossible(i,j,n):
                        Grid[i][j]=n
                        rows[i].add(n)
                        cols[j].add(n)
                        squares[(i//3,j//3)].add(n)
                        solve()
                        Grid[i][j]=0
                        rows[i].remove(n)
                        cols[j].remove(n)
                        squares[(i//3,j//3)].remove(n)
                return
    print(np.matrix(Grid))
    return

In [25]:
solve()

[[2 7 3 5 9 4 8 6 1]
 [4 5 8 6 1 7 3 9 2]
 [1 6 9 8 3 2 4 7 5]
 [9 8 6 4 2 1 7 5 3]
 [3 2 5 9 7 8 1 4 6]
 [7 4 1 3 5 6 2 8 9]
 [8 1 2 7 6 5 9 3 4]
 [6 3 7 2 4 9 5 1 8]
 [5 9 4 1 8 3 6 2 7]]
[[2 7 3 5 9 4 8 6 1]
 [4 5 8 6 1 7 3 9 2]
 [1 6 9 8 3 2 4 7 5]
 [9 8 6 4 2 1 7 5 3]
 [3 2 5 9 7 8 1 4 6]
 [7 4 1 3 5 6 2 8 9]
 [8 1 2 7 6 5 9 3 4]
 [6 9 7 2 4 3 5 1 8]
 [5 3 4 1 8 9 6 2 7]]
